const callData= [
    {
      "logID": 1818,
      "logStatus": 1,
      "logCallEnded": null,
      "exotel_duration": null,
      "id": 1,
      "sid": "fc8027f81aa27f3db8f22615b1ed1712",
      "cust1": "SHAB",
      "cust2": "data 1",
      "cust3": "data 2",
      "cust4": "data 3",
      "cust5": "data 4",
      "cust6": "data 5",
      "cust7": "data 6",
      "cust8": "data 7",
      "cust9": null,
      "cust10": null,
      "cust11": null,
      "cust12": null,
      "cust13": null,
      "cust14": null,
      "cust15": null,
      "cust16": null,
      "cust17": null,
      "cust18": null,
      "cust19": null,
      "cust20": null,
      "cust21": null,
      "cust22": null,
      "cust23": null,
      "cust24": null,
      "cust25": null,
      "max_dispose_time": 20,
      "queueId": 562,
      "name": "Test Call 2",
      "description": "",
      "cust1_name": "customer name",
      "cust2_name": "meta data 1",
      "cust3_name": "meta data 2",
      "cust4_name": "meta data 3",
      "cust5_name": "meta data 4",
      "cust6_name": "meta data 5",
      "cust7_name": "meta data 6",
      "cust8_name": "meta data 7",
      "cust9_name": null,
      "cust10_name": null,
      "cust11_name": null,
      "cust12_name": null,
      "cust13_name": null,
      "cust14_name": null,
      "cust15_name": null,
      "cust16_name": null,
      "cust17_name": null,
      "cust18_name": null,
      "cust19_name": null,
      "cust20_name": null,
      "cust21_name": null,
      "cust22_name": null,
      "cust23_name": null,
      "cust24_name": null,
      "cust25_name": null,
      "leg0_status": null,
      "leg1_status": null,
      "leg_direction": 0,
      "retryInterval": null,
      "call_status": "FRESH"
    },
    {
      "logID": 1820,
      "logStatus": 1,
      "logCallEnded": null,
      "exotel_duration": null,
      "id": 2,
      "sid": "9d50576ffdc1ddcdb049c45b42871712",
      "cust1": "GDV",
      "cust2": "data 1",
      "cust3": "data 2",
      "cust4": "data 3",
      "cust5": "data 4",
      "cust6": "data 5",
      "cust7": "data 6",
      "cust8": "data 7",
      "cust9": null,
      "cust10": null,
      "cust11": null,
      "cust12": null,
      "cust13": null,
      "cust14": null,
      "cust15": null,
      "cust16": null,
      "cust17": null,
      "cust18": null,
      "cust19": null,
      "cust20": null,
      "cust21": null,
      "cust22": null,
      "cust23": null,
      "cust24": null,
      "cust25": null,
      "max_dispose_time": 20,
      "queueId": 562,
      "name": "Test Call 2",
      "description": "",
      "cust1_name": "customer name",
      "cust2_name": "meta data 1",
      "cust3_name": "meta data 2",
      "cust4_name": "meta data 3",
      "cust5_name": "meta data 4",
      "cust6_name": "meta data 5",
      "cust7_name": "meta data 6",
      "cust8_name": "meta data 7",
      "cust9_name": null,
      "cust10_name": null,
      "cust11_name": null,
      "cust12_name": null,
      "cust13_name": null,
      "cust14_name": null,
      "cust15_name": null,
      "cust16_name": null,
      "cust17_name": null,
      "cust18_name": null,
      "cust19_name": null,
      "cust20_name": null,
      "cust21_name": null,
      "cust22_name": null,
      "cust23_name": null,
      "cust24_name": null,
      "cust25_name": null,
      "leg0_status": null,
      "leg1_status": null,
      "leg_direction": 0,
      "retryInterval": null,
      "call_status": "FRESH"
    },
    {
      "logID": 1821,
      "logStatus": 1,
      "logCallEnded": null,
      "exotel_duration": null,
      "id": 3,
      "sid": "3c911fb5149a58f44ad6b18833ff1712",
      "cust1": "shab",
      "cust2": "data 1",
      "cust3": "data 2",
      "cust4": "data 3",
      "cust5": "data 4",
      "cust6": "data 5",
      "cust7": "data 6",
      "cust8": "data 7",
      "cust9": null,
      "cust10": null,
      "cust11": null,
      "cust12": null,
      "cust13": null,
      "cust14": null,
      "cust15": null,
      "cust16": null,
      "cust17": null,
      "cust18": null,
      "cust19": null,
      "cust20": null,
      "cust21": null,
      "cust22": null,
      "cust23": null,
      "cust24": null,
      "cust25": null,
      "max_dispose_time": 20,
      "queueId": 562,
      "name": "Test Call 2",
      "description": "",
      "cust1_name": "customer name",
      "cust2_name": "meta data 1",
      "cust3_name": "meta data 2",
      "cust4_name": "meta data 3",
      "cust5_name": "meta data 4",
      "cust6_name": "meta data 5",
      "cust7_name": "meta data 6",
      "cust8_name": "meta data 7",
      "cust9_name": null,
      "cust10_name": null,
      "cust11_name": null,
      "cust12_name": null,
      "cust13_name": null,
      "cust14_name": null,
      "cust15_name": null,
      "cust16_name": null,
      "cust17_name": null,
      "cust18_name": null,
      "cust19_name": null,
      "cust20_name": null,
      "cust21_name": null,
      "cust22_name": null,
      "cust23_name": null,
      "cust24_name": null,
      "cust25_name": null,
      "leg0_status": null,
      "leg1_status": null,
      "leg_direction": 0,
      "retryInterval": null,
      "call_status": "FRESH"
    },
    {
      "logID": 1823,
      "logStatus": 1,
      "logCallEnded": null,
      "exotel_duration": null,
      "id": 4,
      "sid": "fdba1e28e5ef9401cc690cef096b1712",
      "cust1": "gop",
      "cust2": "data 1",
      "cust3": "data 2",
      "cust4": "data 3",
      "cust5": "data 4",
      "cust6": "data 5",
      "cust7": "data 6",
      "cust8": "data 7",
      "cust9": null,
      "cust10": null,
      "cust11": null,
      "cust12": null,
      "cust13": null,
      "cust14": null,
      "cust15": null,
      "cust16": null,
      "cust17": null,
      "cust18": null,
      "cust19": null,
      "cust20": null,
      "cust21": null,
      "cust22": null,
      "cust23": null,
      "cust24": null,
      "cust25": null,
      "max_dispose_time": 20,
      "queueId": 562,
      "name": "Test Call 2",
      "description": "",
      "cust1_name": "customer name",
      "cust2_name": "meta data 1",
      "cust3_name": "meta data 2",
      "cust4_name": "meta data 3",
      "cust5_name": "meta data 4",
      "cust6_name": "meta data 5",
      "cust7_name": "meta data 6",
      "cust8_name": "meta data 7",
      "cust9_name": null,
      "cust10_name": null,
      "cust11_name": null,
      "cust12_name": null,
      "cust13_name": null,
      "cust14_name": null,
      "cust15_name": null,
      "cust16_name": null,
      "cust17_name": null,
      "cust18_name": null,
      "cust19_name": null,
      "cust20_name": null,
      "cust21_name": null,
      "cust22_name": null,
      "cust23_name": null,
      "cust24_name": null,
      "cust25_name": null,
      "leg0_status": null,
      "leg1_status": null,
      "leg_direction": 0,
      "retryInterval": null,
      "call_status": "FRESH"
    },
    {
      "logID": 1824,
      "logStatus": 1,
      "logCallEnded": null,
      "exotel_duration": null,
      "id": 5,
      "sid": "bbeb9e962643e5967da422416a0b1712",
      "cust1": "shabeer",
      "cust2": "data 1",
      "cust3": "data 2",
      "cust4": "data 3",
      "cust5": "data 4",
      "cust6": "data 5",
      "cust7": "data 6",
      "cust8": "data 7",
      "cust9": null,
      "cust10": null,
      "cust11": null,
      "cust12": null,
      "cust13": null,
      "cust14": null,
      "cust15": null,
      "cust16": null,
      "cust17": null,
      "cust18": null,
      "cust19": null,
      "cust20": null,
      "cust21": null,
      "cust22": null,
      "cust23": null,
      "cust24": null,
      "cust25": null,
      "max_dispose_time": 20,
      "queueId": 562,
      "name": "Test Call 2",
      "description": "",
      "cust1_name": "customer name",
      "cust2_name": "meta data 1",
      "cust3_name": "meta data 2",
      "cust4_name": "meta data 3",
      "cust5_name": "meta data 4",
      "cust6_name": "meta data 5",
      "cust7_name": "meta data 6",
      "cust8_name": "meta data 7",
      "cust9_name": null,
      "cust10_name": null,
      "cust11_name": null,
      "cust12_name": null,
      "cust13_name": null,
      "cust14_name": null,
      "cust15_name": null,
      "cust16_name": null,
      "cust17_name": null,
      "cust18_name": null,
      "cust19_name": null,
      "cust20_name": null,
      "cust21_name": null,
      "cust22_name": null,
      "cust23_name": null,
      "cust24_name": null,
      "cust25_name": null,
      "leg0_status": null,
      "leg1_status": null,
      "leg_direction": 0,
      "retryInterval": null,
      "call_status": "FRESH"
    },
    {
      "logID": 1825,
      "logStatus": 1,
      "logCallEnded": null,
      "exotel_duration": null,
      "id": 6,
      "sid": "2ec5a0caa752d667ac2cf79fddb21712",
      "cust1": "ashwin",
      "cust2": "data 1",
      "cust3": "data 2",
      "cust4": "data 3",
      "cust5": "data 4",
      "cust6": "data 5",
      "cust7": "data 6",
      "cust8": "data 7",
      "cust9": null,
      "cust10": null,
      "cust11": null,
      "cust12": null,
      "cust13": null,
      "cust14": null,
      "cust15": null,
      "cust16": null,
      "cust17": null,
      "cust18": null,
      "cust19": null,
      "cust20": null,
      "cust21": null,
      "cust22": null,
      "cust23": null,
      "cust24": null,
      "cust25": null,
      "max_dispose_time": 20,
      "queueId": 562,
      "name": "Test Call 2",
      "description": "",
      "cust1_name": "customer name",
      "cust2_name": "meta data 1",
      "cust3_name": "meta data 2",
      "cust4_name": "meta data 3",
      "cust5_name": "meta data 4",
      "cust6_name": "meta data 5",
      "cust7_name": "meta data 6",
      "cust8_name": "meta data 7",
      "cust9_name": null,
      "cust10_name": null,
      "cust11_name": null,
      "cust12_name": null,
      "cust13_name": null,
      "cust14_name": null,
      "cust15_name": null,
      "cust16_name": null,
      "cust17_name": null,
      "cust18_name": null,
      "cust19_name": null,
      "cust20_name": null,
      "cust21_name": null,
      "cust22_name": null,
      "cust23_name": null,
      "cust24_name": null,
      "cust25_name": null,
      "leg0_status": null,
      "leg1_status": null,
      "leg_direction": 0,
      "retryInterval": null,
      "call_status": "FRESH"
    }
  
  ];


  export default callData;